kiwigrid/helm-charts

charts/graphite/Chart.yaml, charts/graphite/values.yaml
raised default resources as with the provided ones the readiness check fails
=> graphite - changed default resources

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
* updated fluent-elasticsearch image to 2.4.0
- fixes #
=> updated fluentd-elasticsearch image to 2.4.0

charts/kubernetes-policy-controller/.helmignore, charts/kubernetes-policy-controller/Chart.yaml, charts/kubernetes-policy-controller/README.md, charts/kubernetes-policy-controller/templates/NOTES.txt, charts/kubernetes-policy-controller/templates/_helpers.tpl, charts/kubernetes-policy-controller/templates/clusterrolebinding.yaml, charts/kubernetes-policy-controller/templates/configmap.yaml, charts/kubernetes-policy-controller/templates/deployment.yaml, charts/kubernetes-policy-controller/templates/matches-configmap.yaml, charts/kubernetes-policy-controller/templates/policymatches-configmap.yaml, charts/kubernetes-policy-controller/templates/role.yaml, charts/kubernetes-policy-controller/templates/rolebinding.yaml, charts/kubernetes-policy-controller/templates/service.yaml, charts/kubernetes-policy-controller/templates/webhookconfiguration.yaml, charts/kubernetes-policy-controller/values.yaml
this PR add a helm chart for https://www.openpolicyagent.org/.
This helm chart is helpful to manage cluster policies 
- fixes #
=> add kubernetes-policy-controller chart

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md
=> Updated repo name

charts/graphite/Chart.yaml, charts/graphite/README.md
=> Fixed repo name in example

charts/pull-secret-distributor/.helmignore, charts/pull-secret-distributor/Chart.yaml, charts/pull-secret-distributor/README.md, charts/pull-secret-distributor/templates/NOTES.txt, charts/pull-secret-distributor/templates/_helpers.tpl, charts/pull-secret-distributor/templates/cluster-role.yaml, charts/pull-secret-distributor/templates/cluster-rolebinding.yaml, charts/pull-secret-distributor/templates/deployment.yaml, charts/pull-secret-distributor/templates/serviceaccount.yaml, charts/pull-secret-distributor/values.yaml
adds the helm chart for: https://github.com/kiwigrid/pull-secret-distributor
this tool distibutes pull secretes across namespaces
- fixes #
=> Pull secret distributor

charts/pull-secret-distributor/Chart.yaml, charts/pull-secret-distributor/README.md, charts/pull-secret-distributor/templates/deployment.yaml, charts/pull-secret-distributor/values.yaml
add ignore namespace option for pull-secret-distributor
- fixes #
=> add new option for pull-secret-distributor

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/templates/rbac_role_binding.yaml
Fixed role binding to the default service acc of the namespace
=> Add rolebinding to the service account of the controllers namespace

charts/pull-secret-distributor/Chart.yaml, charts/pull-secret-distributor/values.yaml
update to more stable version 
- fixes #
=> Update pull secret distributor

charts/kubernetes-policy-controller/Chart.yaml, charts/kubernetes-policy-controller/templates/webhookconfiguration.yaml
add namespace selector to explicitly include namespaces 
- fixes #
=> add namespace selector for webhook

charts/zipkin-stackdriver-proxy/.helmignore, charts/zipkin-stackdriver-proxy/Chart.yaml, charts/zipkin-stackdriver-proxy/README.md, charts/zipkin-stackdriver-proxy/templates/NOTES.txt, charts/zipkin-stackdriver-proxy/templates/_helpers.tpl, charts/zipkin-stackdriver-proxy/templates/deployment.yaml, charts/zipkin-stackdriver-proxy/templates/service.yaml, charts/zipkin-stackdriver-proxy/values.yaml
add zipkin stackdriver proxy chart to forward zipkin traces to stackdriver
- fixes #
=> add zipkin-stackdriver-proxy chart

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md
Updates `helm install` examples to use kiwigrid repo rather than stable repo
- [ x] [DCO](https://developercertificate.org) signed
=> Update elasticsearch chart repo

charts/graphite/Chart.yaml, charts/graphite/README.md, charts/graphite/values.yaml
* updated Graphite image to 1.1.5-4
- fixes #
=> updated Graphite image to 1.1.5-4

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/secrets.yaml, charts/hawkbit-update-server/values.yaml
* added hawkbit user & pass env vars
- fixes #
=> hawkbit - added hawkbit user & pass env var

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/templates/deployment.yaml
=> fix hawkbit secret ref

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/templates/deployment.yaml
=> fix hawkbit

.circleci/lint-chart.sh, charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md
=> added upgrade note to the readme

charts/stackdriver-exporter/.helmignore, charts/stackdriver-exporter/Chart.yaml, charts/stackdriver-exporter/README.md, charts/stackdriver-exporter/templates/NOTES.txt, charts/stackdriver-exporter/templates/_helpers.tpl, charts/stackdriver-exporter/templates/deployment.yaml, charts/stackdriver-exporter/templates/gcpserviceaccount.yaml, charts/stackdriver-exporter/templates/secret.yaml, charts/stackdriver-exporter/values.yaml
- add helm chart for stackdriver exporter 
- this exporter exports stackdriver metrics into prometheus
=> add stackdriver-exporter

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/ingress.yaml, charts/hawkbit-update-server/templates/secrets.yaml, charts/hawkbit-update-server/values.yaml
* added new nginxClientMaxBodySize variable
* fixed user vars
- fixes #
=> [hawkbit] added new nginxClientMaxBodySize variable & fixed user vars

charts/any-resource/.helmignore, charts/any-resource/Chart.yaml, charts/any-resource/README.md, charts/any-resource/templates/NOTES.txt, charts/any-resource/templates/_helpers.tpl, charts/any-resource/templates/any-resources.yaml, charts/any-resource/values.yaml
=> Add any-resource chart

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/ingress.yaml, charts/hawkbit-update-server/values.yaml
…nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md\#custom-max-body-size
- fixes #
=> Fix Custom max body size

charts/stackdriver-exporter/Chart.yaml, charts/stackdriver-exporter/README.md, charts/stackdriver-exporter/templates/_helpers.tpl, charts/stackdriver-exporter/templates/deployment.yaml, charts/stackdriver-exporter/templates/secret.yaml, charts/stackdriver-exporter/values.yaml
- fix stackdriver exporter chart
=> Fix stackdriver exporter

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/values.yaml
*  added ssl verify option
- fixes # https://github.com/kiwigrid/helm-charts/issues/58
=> [fluentd-elasticsearch] added ssl verify option

.circleci/ct.yaml, charts/prometheus-thanos/.helmignore, charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/ci/test-values.yaml, charts/prometheus-thanos/requirements.yaml, charts/prometheus-thanos/templates/NOTES.txt, charts/prometheus-thanos/templates/_helpers.tpl, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/querier-service.yaml, charts/prometheus-thanos/templates/store-gateway-deployment.yaml, charts/prometheus-thanos/templates/store-gateway-service.yaml, charts/prometheus-thanos/values.yaml
=> add thanos helm chart

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/clusterrolebinding.yaml, charts/fluentd-elasticsearch/templates/service-account.yaml, charts/fluentd-elasticsearch/values.yaml
The current code does not use the good template. It should use fluentd-elasticsearch.serviceAccountName instead of fluentd-elasticsearch.fullname
- fixes #63 
=> Fix service account name

charts/fluentd-elasticsearch/Chart.yaml
=> fixed sources link

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/ingress.yaml, charts/hawkbit-update-server/values.yaml
* removed hardcoded nginx annotation to be compatible to other load balancers
- fixes #
=> removed hardcoded nginx annotation

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/values.yaml
- add option to mount volumes for thanos querier
=> add option to mount volumes

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
* updated fluentd docker image to 2.5.1
- fixes #
=> updated fluentd docker image to 2.5.1

charts/secret-replicator/Chart.yaml, charts/secret-replicator/README.md, charts/secret-replicator/values.yaml
=> update image version

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/cluster-service.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/store-gateway-deployment.yaml, charts/prometheus-thanos/values.yaml
=> enable prometheus thanos cluster mode

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/ci/test-values.yaml, charts/prometheus-thanos/templates/compact-deployment.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/store-gateway-deployment.yaml, charts/prometheus-thanos/values.yaml
- enable compact service for thanos
=> Enable compacter

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/compact-deployment.yaml, charts/prometheus-thanos/values.yaml
=> fix extraenv for thanos

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/templates/stateful_set.yaml
=> escape env var

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
=> Adding option to set updateStrategy

charts/ingress-annotator/.helmignore, charts/ingress-annotator/Chart.yaml, charts/ingress-annotator/README.md, charts/ingress-annotator/templates/NOTES.txt, charts/ingress-annotator/templates/_helpers.tpl, charts/ingress-annotator/templates/configmap.yaml, charts/ingress-annotator/templates/deployment.yaml, charts/ingress-annotator/values.yaml
Signed-off-by: Rico Pahlisch <rico.pahlisch@kiwigrid.com>
- add ingress annotator chart
=> add ingress annotator

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/values.yaml
* added java options via env var 
* updated image version to 0.3.0M2
- fixes #
=> [hawkbit] added java options via env var and updated image version to 0.3.0M2

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/values.yaml
* made java opts optional via extra env var
- fixes #
=> Hawkbit - made java opts optional via extra env var

charts/error-pages/.helmignore, charts/error-pages/Chart.yaml, charts/error-pages/README.md, charts/error-pages/templates/NOTES.txt, charts/error-pages/templates/_helpers.tpl, charts/error-pages/templates/deployment.yaml, charts/error-pages/templates/ingress.yaml, charts/error-pages/templates/service.yaml, charts/error-pages/values.yaml
=> add helm chart for global error pages

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
sorry @monotek, @axdotl   I've done a mistake on my previous PR I switch volume and volumeMount
this will fix it
=> fixup-feature-fluentd-allowed-path

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
bump to the new docker image of fluentd-elasticsearch
=> increase docker image of fluentd-elasticsearch

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compact-deployment.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/store-gateway-deployment.yaml, charts/prometheus-thanos/values.yaml
=> Thanos pod labels

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/ci/test-values.yaml, charts/prometheus-thanos/templates/ruler-configmap.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/values.yaml
=> add thanos ruler

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/ruler-clusterrole.yaml, charts/prometheus-thanos/templates/ruler-clusterrolebinding.yaml, charts/prometheus-thanos/templates/ruler-serviceaccount.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
Signed-off-by: Rico Pahlisch <rico.pahlisch@kiwigrid.com>
- fixes #
=> move store gateway to stateful set and add ruler sidecar

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/secrets.yaml, charts/hawkbit-update-server/values.yaml
* currently username / password vars for hawkbit login seem to be ignored.
* even with the change from 
SECURITY_USER_NAME to SPRING_SECURITY_USER_NAME and SECURITY_USER_PASSWORD to SPRING_SECURITY_USER_PASSWORD.
When trying to use both vars the login did not work at all.
- fixes #
=> Hawkbit - fixed username & password vars

.github/PULL_REQUEST_TEMPLATE.md, charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
* updated fluentd docker image to 2.6.0
- fixes #
fixes parts off: https://github.com/kiwigrid/helm-charts/issues/116
=> [fluentd-elasticsearch] updated fluentd docker image to 2.6.0

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
changed docker image repo to quay.io as gcr.io costs were to high
- fixes #
=> [fluend-elasticsearch] changed docker image repo to quay.io

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md
=> Update README and adjust chart metadata

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] update thanos version

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] Make ruler flag rule-file configurable

.circleci/config.yml, .circleci/kind-config.yaml
* Bump versions of KIND, chart-testing, gcloud-kubectl-helm
* Unify stage names
* Added k8s v1.14 stage
=> Update CI pipeline

charts/spring-cloud-config-server/.helmignore, charts/spring-cloud-config-server/Chart.yaml, charts/spring-cloud-config-server/README.md, charts/spring-cloud-config-server/templates/NOTES.txt, charts/spring-cloud-config-server/templates/_helpers.tpl, charts/spring-cloud-config-server/templates/deployment.yaml, charts/spring-cloud-config-server/templates/ingress.yaml, charts/spring-cloud-config-server/templates/secret.yaml, charts/spring-cloud-config-server/templates/service.yaml, charts/spring-cloud-config-server/values.yaml
=> [spring-cloud-config-server] Spring cloud config server

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/clusterrole.yaml, charts/fluentd-elasticsearch/templates/clusterrolebinding.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/templates/metrics-service.yaml, charts/fluentd-elasticsearch/templates/pod-security-policy.yaml, charts/fluentd-elasticsearch/templates/prometheusrule.yaml, charts/fluentd-elasticsearch/templates/role.yaml, charts/fluentd-elasticsearch/templates/rolebinding.yaml, charts/fluentd-elasticsearch/templates/service-account.yaml, charts/fluentd-elasticsearch/templates/service.yaml, charts/fluentd-elasticsearch/templates/servicemonitor.yaml
=> [fluentd-elasticsearch] remove obsolete flag

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/configmap.yaml, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/secrets.yaml, charts/hawkbit-update-server/values.yaml
- to be more flexible with hawkbit server images
=> [hawkbit-update-server] rework hawkbit update server to be more flexible

charts/fluentd-elasticsearch/Chart.yaml
Signed-off-by: Brian <brian.nutt@rakuten.com>
Updates image version to match appVersion in the chart.
- fixes #
=> [fluentd-elasticsearch]: Update app version to match image version

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md
Fixes typos in the README.
N/A
none
=> [fluentd-elasticsearch] fixed typos in README

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/querier-service.yaml, charts/prometheus-thanos/templates/ruler-configmap.yaml, charts/prometheus-thanos/templates/ruler-service.yaml, charts/prometheus-thanos/templates/ruler-serviceaccount.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-service.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] Avoid resource creation if a specific thanos component is not desired

charts/keycloak-controller/Chart.yaml, charts/keycloak-controller/README.md, charts/keycloak-controller/templates/deployment.yaml, charts/keycloak-controller/values.yaml
=> [keycloak-controller] Add support for CONTROLLER_NAMESPACED flag

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
=> [fluentd-elasticsearch] allow plugins install

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/templates/deployment.yaml
=> Fix broken manifest because of inappropriate function usage

README.md, charts/fluentd-elasticsearch/Chart.yaml
[fluentd-elasticsearch] Update README.md with IBM IKS installation
Update README.md with details on how to deploy fluentd-elasticsearch helm char on IBM IKS
- fixes # https://github.com/kiwigrid/helm-charts/issues/168
=> [fluentd-elasticsearch] Update README.md with IBM IKS installation

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
- fixes https://github.com/kiwigrid/k8s-configmap-watcher/issues/2
=> update sidecar version

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/values.yaml
=> update gcp-serviceaccount-controller version

charts/keycloak-controller/Chart.yaml, charts/keycloak-controller/README.md, charts/keycloak-controller/values.yaml
=> Update because of kiwigrid/keycloak-controller#12

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/service-account.yaml, charts/fluentd-elasticsearch/values.yaml
AWS recently added support for [IAM roles for Service accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) for which Service Accounts need an annotation.
=> [fluentd-elasticsearch]: Adding support for annotations on fluentd-elasticsearch serviceaccount

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/values.yaml
=> Adjust example service annotation

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
https://github.com/kiwigrid/helm-charts/issues/217
- fixes #217
=> [fluentd-elasticsearch] fixes #217

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
<!--
Make resources, port and address configurable for awsSidecar 
- fixes #208 
- fixed #196 
- [x ] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)
=> [fluentd-elasticsearch] Fix for #207 and #196

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/README.md, charts/ditto-digital-twins/templates/nginx-configmap.yaml, charts/ditto-digital-twins/values.yaml
=> Enable OIDC configuration

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/README.md, charts/ditto-digital-twins/templates/nginx-configmap.yaml, charts/ditto-digital-twins/templates/nginx-ingress.yaml, charts/ditto-digital-twins/values.yaml
=> Add ingress resource and fix nginx config for oidc

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/README.md, charts/ditto-digital-twins/templates/gateway-deployment.yaml, charts/ditto-digital-twins/templates/nginx-configmap.yaml, charts/ditto-digital-twins/values.yaml
=> Adjust security configuration for devops endpoint

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/README.md, charts/ditto-digital-twins/templates/NOTES.txt, charts/ditto-digital-twins/templates/gateway-deployment.yaml, charts/ditto-digital-twins/templates/gateway-secret.yaml, charts/ditto-digital-twins/values.yaml
@monotek Hope it's better now ;)
=> Handle passwords via secret

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/templates/concierge-deployment.yaml, charts/ditto-digital-twins/templates/connectivity-deployment.yaml, charts/ditto-digital-twins/templates/gateway-deployment.yaml, charts/ditto-digital-twins/templates/nginx-deployment.yaml, charts/ditto-digital-twins/templates/policies-deployment.yaml, charts/ditto-digital-twins/templates/things-deployment.yaml, charts/ditto-digital-twins/templates/thingssearch-deployment.yaml
=> Add checksum config annotations to trigger pod restart on config change

.ci/deploy-chart.sh, .ci/install-chart.sh, .ci/lint-chart.sh, .github/workflows/ci.yaml, .github/workflows/deploy.yaml, charts/fluentd-elasticsearch/Chart.yaml
=> WIP - CI Test2

.ci/deploy-chart.sh, .github/workflows/deploy.yaml
=> fixed ci deploy

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
* update image to v2.8.0
- fixes #
=> [fluentd-elasticsearch] update image to v2.8.0

.ci/deploy-chart.sh, .github/workflows/deploy.yaml
=> Fix deploy

.ci/deploy-chart.sh, .github/workflows/deploy.yaml
=> set helm home in helm command

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/templates/concierge-networkpolicy.yaml, charts/ditto-digital-twins/templates/connectivity-networkpolicy.yaml, charts/ditto-digital-twins/templates/policies-networkpolicy.yaml, charts/ditto-digital-twins/templates/thingssearch-networkpolicy.yaml
I just made some changes which were already applied to the Ditto chart in eclipse project.
This PR is mainly to verify CI pipeline which is now based on Github Actions.
=> Do not allow unnecessary network communication

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
=> [fluentd-elasticsearch ]fixed app version & some markdown fixes in readme

charts/keycloak-controller/Chart.yaml, charts/keycloak-controller/README.md, charts/keycloak-controller/values.yaml
=> Bump keycloak controller version

.ci/check-for-chart-changes.sh, .github/workflows/ci.yaml, .github/workflows/deploy.yaml, charts/fluentd-elasticsearch/Chart.yaml
* use actions from helm repo 
* run only on chart changes
- fixes #
=> WIP - [ci] use actions from helm repo / run only on chart changes

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/requirements.yaml, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] updated thanos to 0.9.0

charts/ditto-digital-twins/Chart.yaml, charts/ditto-digital-twins/README.md
=> Deprecate Ditto chart

.github/workflows/ci.yaml
* use relative path for ct config (fixed unused timeout etc)
* updated kubernetes kind images to latest versions
* put lint bash scripts in own job
- fixes #
=> use relative paths for ct config

.github/workflows/ci.yaml
=> use relative paths everywhere

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml
JSON parser attempts to parse the `time` field by default ( see `time_key` default value at https://docs.fluentd.org/configuration/parse-section ). If such an embedded JSON contained a `time` field, Fluentd would attempt to parse it using some default time format which would most likely be wrong, overriding the event time parsed from the docker log. Therefore fluentd-elasticsearch shouldn't parse the `time` field of an embedded JSON and use the `time` provided by the Docker log file in the former parser.
- probably fixes #199
=> [fluentd-elasticsearch] Do not parse time field in the embedded json

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] update thanos to 0.10.0

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md
Signed-off-by: fsschmitt <492108+fsschmitt@users.noreply.github.com>
Updates documentation to reflect the changes regarding upgrading to the latest version of Thanos (v0.10.0)
@rpahli 
@axdotl 
=> [prometheus-thanos] Update Readme with Thanos v0.10.0

.github/workflows/ci.yaml, charts/stackdriver-exporter/Chart.yaml, charts/stackdriver-exporter/README.md, charts/stackdriver-exporter/templates/deployment.yaml, charts/stackdriver-exporter/values.yaml
* added prometheus.io/scrape-slow annotation option (https://github.com/helm/charts/commit/dd4445f178cb738c7d93d671d28d38eda5847576#diff-96ee383c960276a9123176de8080798c)
- fixes #
=> [stackdriver-exporter] added prometheus.io/scrape-slow annotation option

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/bucket-web-serviceaccount.yaml, charts/prometheus-thanos/templates/compact-serviceaccount.yaml, charts/prometheus-thanos/templates/querier-serviceaccount.yaml, charts/prometheus-thanos/templates/ruler-serviceaccount.yaml, charts/prometheus-thanos/templates/store-gateway-serviceaccount.yaml
=> [prometheus-thanos] Fix wrong indentation

.github/workflows/ci.yaml
* updates k8s versions
* removed k8s 1.11 (beacuse of storage class install error)
* fixed node varname
- fixes #
=> fix github action matrix

.github/check-for-chart-changes.sh, .github/kubeval.sh, .github/workflows/ci.yaml, charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
* updated fluentd image to 3.0.0
* changed entrypoint as its changed in the new image too
* use latest for aws sidcar image as 0.9 tag is not available anymore
- fixes #
=> [fluentd-elasticsearch] updated fluentd image

.github/kubeval.sh, .github/workflows/ci.yaml, charts/fluentd-elasticsearch/Chart.yaml
=> added kubeval to github action

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
=> [fluentd-elasticsearch] use version 0.9 of aws proxy again

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md
Update README with latest changes (compactor) and unify PV `enabled` and `existingClaim` across all components
- additional changes for PR #303
Consistency look as a lot of users not looking into `values.yaml` file but look at README.
=> [prometheus-thanos] Updates for PV in README

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/compactor/statefulset.yaml, charts/prometheus-thanos/templates/ruler/statefulset.yaml, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml
Added logic for existingClaim for `compact`, `ruler` and `storeGateway`
Signed-off-by: Sergei Shishov <sshishov.sshishov@gmail.com>
Adds support of `existingClaim` for all components which are using persistent storage.
- fixes #
For being even more clear and avoid usage of a lot of IFs, we can create `pvc.yaml` for every component and add the logic of creation PVC there instead of relying on a template. Like it is done in `prometheus` repo [here](https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-pvc.yaml)
=> [prometheus-thanos] Support of existingClaim

charts/keycloak-controller/Chart.yaml, charts/keycloak-controller/values.yaml
Update keycloak controller to 2.0.0
* corresponds to https://github.com/kiwigrid/keycloak-controller/issues/20
- [x ] Chart Version bumped (if the pr is an update to an existing chart)
=> [keycloak-controller]update keycloak controller

.github/kubeval.sh, .github/lint-scripts.sh, .github/workflows/ci.yaml, charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml, charts/prometheus-thanos/values.yaml
…ult)
* updates thanos to 0.12.0
* change binary header option name and changed it from an option you have to enable to an option you have to disable as enabling it is the default in thanos 0.12.0
* use 10Gi for all pvc to be consistent 
- fixes #
=> [prometheus-thanos] update thanos to 0.12.0 and change index header option

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
* remove plugin install option
- fixes https://github.com/kiwigrid/helm-charts/issues/326
=> [fluentd-elasticsearch] remove plugin install option

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
=> [fluentd-elasticsearch] Upgrade fluentd docker image to v3.0.1.

charts/keycloak-controller/Chart.yaml, charts/keycloak-controller/README.md
=> [keycloak-controller] fixed readme

charts/influxdb-backup/Chart.yaml, charts/influxdb-backup/README.md, charts/influxdb-backup/templates/cronjob.yaml, charts/influxdb-backup/templates/secrets.yaml
=> [Influxdb-backup] fix gsutil upload

charts/influxdb-backup/Chart.yaml, charts/influxdb-backup/README.md, charts/influxdb-backup/templates/NOTES.txt, charts/influxdb-backup/templates/configmap.yaml, charts/influxdb-backup/templates/cronjob.yaml, charts/influxdb-backup/templates/secrets.yaml
=> [Influxdb-backup] fix gsutil with exisitng secret

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
- fixes # https://github.com/kiwigrid/helm-charts/issues/361
=> [fluentd-elasticsearch] update fluentd image to 3.0.2

charts/influxdb-backup/Chart.yaml, charts/influxdb-backup/README.md, charts/influxdb-backup/templates/NOTES.txt, charts/influxdb-backup/templates/configmap.yaml, charts/influxdb-backup/templates/cronjob.yaml, charts/influxdb-backup/templates/secrets.yaml, charts/influxdb-backup/values.yaml
=> [influxdb-backup] added restore option

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
=> Added setter for logstash prefixSeparator and dateformat

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/role.yaml, charts/fluentd-elasticsearch/templates/rolebinding.yaml
=> [fluentd-elasticsearch] Update rbac apiversion

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/bucket-web/deployment.yaml
* fix thanos bucket-web deployment
- fixes #
=> [proemtehus-thanos] fix thanos bucket-web deployment

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Add optional support for using existing ILM policies or creating new ILM policies for the index
- fixes #379
=> [fluentd-elasticsearch] Add ilm configuration

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
=> [fluentd-elasticsearch] remove ilm config from daemonset if unused

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml, charts/prometheus-thanos/values.yaml
1. Updated to [Thanos 0.14.0](https://github.com/thanos-io/thanos/releases/tag/v0.14.0)
1. Removed flag for --store.disable-index-header which was removed in this release
- fixes #
=> [prometheus-thanos] Update to Thanos 0.14.0

charts/graphite/Chart.yaml, charts/graphite/README.md, charts/graphite/templates/statefulset.yaml, charts/graphite/values.yaml
This allows us to set environment variables for the underlying graphite Pod. The docker container that the graphite helm chart uses allows us to set configuration for the Graphite Web application via environment variables. However this chart does not currently allow us to set any Environment Variables, nor any other way of interacting with the underlying docker container
Upstream Docker Container:
https://github.com/graphite-project/docker-graphite-statsd
- fixes #
values.yaml
```
env:
- name: example-name
value: example-value
```
```
$ helm template ./
$
env:
- name: "STATSD_INTERFACE"
value: udp
- name: "GRAPHITE_TIME_ZONE"
value: Etc/UTC
- name: example-name
value: …
```
=> [graphite] add ability to pass env values to Graphite Pod

charts/kubernetes-policy-controller/Chart.yaml, charts/kubernetes-policy-controller/templates/deployment.yaml
=> [kubernetes-policy-controller] update k8s api

charts/graphite/Chart.yaml, charts/graphite/templates/ingress.yaml
=> [graphite] update k8s api

charts/error-pages/Chart.yaml, charts/error-pages/templates/ingress.yaml
=> [error-pages]update k8s api

.github/ct.yaml, .github/deploy-chart.sh, charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/ci/test-values.yaml, charts/prometheus-thanos/requirements.yaml, charts/prometheus-thanos/templates/querier/deployment-hpa.yaml, charts/prometheus-thanos/templates/store-gateway/statefulset-hpa.yaml
=> [thanos] update k8s api

.github/workflows/ci.yaml, charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/templates/gcpnamespacerestriction_crd.yaml, charts/gcp-serviceaccount-controller/templates/gcpserviceaccount_crd.yaml
=> [gcp-serviceaccount-controller] update k8s api

charts/fluentd-elasticsearch/Chart.yaml, charts/graphite/Chart.yaml, charts/graphite/templates/ingress.yaml
=> [Graphite] fix ingress api

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/bucket-web/deployment.yaml, charts/prometheus-thanos/templates/compactor/statefulset.yaml, charts/prometheus-thanos/templates/ruler/statefulset.yaml, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml
This allows us to pass additional flags that have new line characters and/or quotation marks in them. One specific example of this is the "tracing.config" flag that takes a YAML string that may contain new line characters, spaces and quotation marks. When this is the case, the provided YAML gets broken and becomes invalid.
We did this for Thanos Querier previously in https://github.com/kiwigrid/helm-charts/pull/419. This PR does the same for all Thanos components that accept additional args.
Signed-off-by: Emre Kartoglu <iemrek@gmail.com>
* I have tested the changes in a private setup.
* Apologies I should probably have included this in the PR https://github.com/kiwigrid/helm-charts/pull/419
=> [prometheus-thanos] Wrap all thanos additional args in quotes

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/templates/gcpnamespacerestriction_crd.yaml, charts/gcp-serviceaccount-controller/templates/gcpserviceaccount_crd.yaml, charts/gcp-serviceaccount-controller/values.yaml
=> fix gcp service account controller

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/templates/gcpnamespacerestriction_crd.yaml, charts/gcp-serviceaccount-controller/templates/gcpserviceaccount_crd.yaml
=> Fix gcp sa controller

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/receiver/statefulset.yaml
=> [prometheus-thanos] : Adding missing volumemount template for receiver

.github/check-for-chart-changes.sh, .github/deploy-chart.sh, .github/kubeval.sh, .github/lint-scripts.sh, .github/workflows/ci.yaml, charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/receiver/hashring-configmap.yaml, charts/prometheus-thanos/templates/receiver/statefulset.yaml
this fixes the receiver hashring configmap name to include the fullname
=> [prometheus-thanos] fix receiver configmap

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md
Updates the documentation of a specific property in the README.
=> [prometheus-thanos] - Fix default retentionResolution5m in README.md

charts/spring-cloud-config-server/Chart.yaml, charts/spring-cloud-config-server/README.md, charts/spring-cloud-config-server/templates/deployment.yaml, charts/spring-cloud-config-server/templates/secret.yaml, charts/spring-cloud-config-server/values.yaml
Signed-off-by: IndPnDay <github@indpnday.com>
You can use the Github  "Deploy keys" section to authenticate.
=> - [spring-cloud-config-server] Added Github ssh authentication

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
This PR updates the Thanos containers to the latest released version.
- updates thanos to latest version
=> [prometheus-thanos]  : update thanos to 0.23.1

.github/workflows/ci.yaml
=> update k8s versions

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
What this PR does / why we need it:
This PR updates the Thanos containers to the latest released version.
Which issue this PR fixes
(optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged)
updates thanos to latest version
=> [prometheus-thanos] : update thanos to 0.27.0

charts/graphite/Chart.yaml
=> [graphite] Bump to 1.1.10-3
