charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR allows user to specify priority class name for pods (see docs [here](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/))
=> [fluentd-elasticsearch] add option to specify priority class for pods

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
`[[ .. ]]` is [a bashism](https://stackoverflow.com/a/47576482) and won't work when called with `/bin/sh`, meaning the LivenessProbe as written will not be triggered for stuck or not-live fluentd containers.
Annoyingly, `/bin/sh` will show an error when called this way:
```bash
root@fluentd-7mprs:/# sh liveness.sh
liveness.sh: 8: liveness.sh: [[: not found
liveness.sh: 15: liveness.sh: [[: not found
```
... But still exit with a non-error return code!
```bash
root@fluentd-7mprs:/# /bin/sh liveness.sh
liveness.sh: 8: liveness.sh: [[: not found
liveness.sh: 15: liveness.sh: [[: not found
root@fluentd-7mprs:/# echo $?
0
```
Anyway; this test doesn't need the `[[` syntax and works properly with the POSIX-compliant `[`.
cc Chart owners @monotek @axdotl :)
[Place an '[x]' (no spaces) in all …
=> Fix Fluentd LivenessProbe

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This change adds optional authentication parameters to the chart to be used with Elasticsearch instances with auth enabled (via XPack, proxy, etc.).  
I've tested this against an authenticated and non-authenticated cluster. Leaving the user/password parameters empty effectively ignores them.
=> Fluentd Elasticsearch Auth

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
Turns out the LivenessProbe condition is actually well broken, and
fixing the bashism (#40) only uncovered the underlying issue with the logic.
The probe checks that the pod is still alive by running the following
command:
`find /var/log/fluentd-buffers -type f -newer /tmp/marker-stuck -print -quit`
This checks if any _regular_ file exists under `/var/log/fluentd-buffers`
that is more recent than a predetermined time, and will return an empty
string otherwise.
The issue is... These buffers are temporary and volatile, they get created and
deleted constantly. Here is an example of running that check every second on a
running fluentd:
```
root@fluentd-eks-playground-jdc8m:/# LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
root@fluentd-eks-playground-jdc8m:/# …
```
=> Fix Fluentd liveness probe

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Fixes the `STUCK_THRESHOLD_SECONDS` variable in the liveness probe to allows it to be set via env var.  Previously it was always set to the same value as `LIVENESS_THRESHOLD_SECONDS`.
=> Fixing liveness probe

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/values.yaml
Logs in json format not being properly parsed in kibana.
Using config as per k8s repo fixes this. Thanks to @monotek for the info.
=> [stable/fluentd-elasticsearch] Use config from k8s repo

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/prometheusrule.yaml, charts/fluentd-elasticsearch/templates/servicemonitor.yaml, charts/fluentd-elasticsearch/values.yaml
Signed-off-by: Pavel Zilke <zidex@altlinux.org>
Added templates for ServiceMonitor and PrometheusRule to fluentd-elasticsearch chart
=> Added support for Prometheus ServiceMonitor and PrometheusRule

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Adds 'affinity' configuration to the fluentd-elasticsearch chart.
`nodeSelector` is sometimes too restrictive; in our case we'd like to deploy this to all non-master nodes automatically without needing to apply extra labels, but there could be more imaginative cases too.
None.
=> Add affinity configuration to fluentd-elasticsearch

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR adds a new configuration `aws` of type bool that allows deploying a sidecar proxy to handle signing requests to Amazon Web Services managed Elasticsearch service.
* See #81 (not a bug, a feature).
=> Added support for deploying a sidecar for signing requests sent to Amazon AWS Elasticsearch.

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/templates/pod-security-policy.yaml, charts/fluentd-elasticsearch/values.yaml
Every K8S distrib (such CFCR the K8S opensource by Cloudfoundry) doesn't store log at the same place as your default.
This PR allows to customize where the default mountPath are located and apply changment to the podsecuritypolicy according the new mountPath. The default value are the previous defined values.
https://github.com/kiwigrid/helm-charts/issues/96
- fixes #96
@monotek 
@axdotl 
=> allows to customize the mount path

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
It allows to change the default FLUENTD_ARGS (fluentd--no-supervisor -q) to add by example -vv (fluentd--no-supervisor -q -vv) 
why I need it: I want to be able to run fluentd with full log trace 
=> Add fluentd args

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
With last changes in fluentd daemonset spec in the middle of the `VolumeMounts` list `livenessProbe` was added for some reason, making use of `extraVolumeMounts` impossible. This PR should fix that.
Maybe some testing framework could be implemented to test those things? Smth like [bats](https://github.com/bats-core/bats-core) maybe?
=> fix(fluentd-elasticsearch): move extraVolumeMounts part to render correct yaml

charts/gcp-serviceaccount-controller/Chart.yaml, charts/gcp-serviceaccount-controller/README.md, charts/gcp-serviceaccount-controller/templates/NOTES.txt, charts/gcp-serviceaccount-controller/templates/secret.yaml, charts/gcp-serviceaccount-controller/templates/stateful_set.yaml, charts/gcp-serviceaccount-controller/values.yaml
Signed-off-by: Tim Jespers <t.jesp3rs@gmail.com>
This PR allows the helm operator to use a pre-existing kubernetes secret instead of supplying their base64 service account keyfile as a release value. Doing so allows the operator to keep the service account keyfile completely out of helm and/or source-control when storing their value file in a git repository.
=> Adding option to use pre-existing secrets

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
Signed-off-by: Chris O'Brien <chrisob91@gmail.com>
@monotek @axdotl 
This PR fixes a bug introduced in #82, which breaks service ports when `awsSigningSidecar.enabled=true` and service ports are defined.
- fixes #119
=> [fluentd-elasticsearch] Fix ports block in daemonset

charts/graphite/Chart.yaml, charts/graphite/templates/statefulset.yaml
- Changed the mountPath in the statefulset for udp and tcp configs to
match the one loaded by the statsd process
Fixes an issue with configmaps for statsd in the graphite chart.
- fixes #129 
=> [graphite] Map udp and tcp configs to the correct path

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/prometheusrule.yaml
Signed-off-by: Brian <brian.nutt@rakuten.com>
Fix expression for FluentdNodeDown alerts, the job name is based off the name of the service, currently it does not match the name of the service for any release as the service is called "fluentd-elasticsearch.fullname" while it looks for {{ .Release.Name }}.
- fixes #
=> [fluentd-elasticsearch] Fix FluentdNodeDown rules

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml
Instead of looking for "thanos-prometheus-thanos-ruler-token-...",
thanos ruler will now look for "prometheus-thanos-ruler-token-...".
The wrong variable is referenced when creating the `serviceAccount` key. Using `prometheus-thanos.name` instead of `prometheus-thanos.fullname` means that the lookup service account is `thanos-prometheus-thanos-ruler-token-...` rather than `prometheus-thanos-ruler-token-...`.
This will mean that we no longer have to manually edit the statefulset to point at the correct account name.
- fixes #
=> [prometheus-thanos] Fix for misnaming the service account.

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/NOTES.txt, charts/fluentd-elasticsearch/templates/metrics-service.yaml, charts/fluentd-elasticsearch/templates/service.yaml, charts/fluentd-elasticsearch/templates/servicemonitor.yaml, charts/fluentd-elasticsearch/values.yaml
This PR changes the way service are set up in the Chart. 
Until now, you had to define a service for the servicemonitor, but in the case several service ports were needed (e.g syslog forwarder), every svc had to be one of NodePort, ClusterIP or LoadBalancer (you don't necessary want your metrics svc to be a nodePort)
In addition, the servicemonitor would range over the list of svc port, but in the end the Kubernetes object was taking only one "port" selector.
Thats why I feature-flipped the creation of a metrics-svc, using the `serviceMonitor.enabled` boolean, and changed the `service` structure so that you can define several services of any type you want (per service).
This issue fixes a bug of ranging over the list of service ports and displaying multiple "ports" in the serviceMonitor …
=> [fluentd-elasticsearch] Changed the way services are templatized

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/values.yaml
Empty keys have been populated with empty structures of their expected type, i.e. an array is [], object {}, to reduce yaml related warnings when deploying with helm. 
Helm raises a warning when a nil value is populated with a value of another type. So leaving keys just as `keyname:` results in helm perceiving that these keys have a type of `<nil>`.
- fixes #
None
=> [prometheus-thanos] Populated previously empty keys

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/secrets.yaml, charts/hawkbit-update-server/values.yaml
Signed-off-by: Brandon Schmitt <Brandon.Schmitt@kiwigrid.com>
It adds Docker image pull secrets used for private repositories. Moreover, it adds support for OpenID Connect.
OpenID Connect is not yet supported by the official hawBit project. However, a pull request has been opened concerning this feature. See https://github.com/eclipse/hawkbit/pull/865.
This commit covers the changes introduced by that pull request.
The configuration uses the nested value `oidc`. The feature can be enabled by setting `oidc.enabled=true`.
In that case the following, additional values must be set:
- `oidc.clientId`
- `oidc.clientSecret`
- `oidc.issuerUri`
- `oidc.authorizationUri`
- `oidc.tokenUri`
- `oidc.userInfoUri`
- `oidc.jwkSetUri`
The liveness and readiness probe has been changed accordingly to use a …
=> [hawkbit-update-server] Added Docker image pull secrets and OpenID Connect support

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md
Signed-off-by: Brandon Schmitt <Brandon.Schmitt@kiwigrid.com>
The PR https://github.com/kiwigrid/helm-charts/pull/132 did not document the newly introduced OpenID Connect values. This PR corrects that.
=> [hawkbit-update-server] Document the OIDC values.

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/NOTES.txt, charts/fluentd-elasticsearch/templates/service.yaml
Adds a ClusterIP as default value for each service that is created from ports map in values. It is needed because it is intuitive that ClusterIP is used most of the times and it is easier to add a type to a port if needed and not add for each port
```
ports:
- name: prom-metrics
port: 24231
- name: forwarder
port: 24224
-  name: some_new_port
port: 9999
```
Instead of:
```
ports:
- name: prom-metrics
port: 24231
type: ClusterIP
- name: forwarder
port: 24224
type: ClusterIP
-  name: some_new_port
port: 9999
```
Added another branch because of missing signoff, cannot resolve the old unfortunately
=> [fluentd-elasticsearch] Service port type default value - 2

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/values.yaml
@monotek 
#127 introduced a bug which breaks any configurations with the following values override:
```
serviceMonitor:
enabled: true
```
This PR simply re-adds the `serviceMonitor.path: /metrics` default value that was (mistakenly?) removed in  #127.
This is the second (or third?) time I've encountered a breaking bug since this chart has moved here from helm/charts. Maybe PR reviews/CI could be a bit more comprehensive?
=> [fluentd-elasticsearch] Fix bug introduced in #127

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR makes global log level configurable from values.yaml under elasticsearch section.
In configmaps.yaml, @log_level now takes specified values from OUTPUT_LOG_LEVEL environment variable
=> [fluentd-elasticsearch] make log level configurable

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR allows the path for elasticsearch to be specified. Currently, only host/scheme/port can be specified
None
=> [fluentd-elasticsearch] Allow elasticsearch path to be specified

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
This makes it possible to get the Elasticsearch password from a
secret instead of storing it in plain text, e.g.:
```
elasticsearch:
auth:
enabled: true
user: elastic
password: ""
secret:
- name: OUTPUT_PASSWORD
secret_name: elasticsearch
secret_key: password
```
I couldn't find a way to get the password from a secret without this change, please let me know if I missed something. There's probably a nicer way of solving this but this should at least be backwards compatible.
=> [fluentd-elasticsearch] Make auth.password value optional

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Signed-off-by: Lee Spottiswood <lee.spottiswood@ukfast.co.uk>
This PR allows the `type_name` directive to be specified, and omitted when value is empty
=> [fluentd-elasticsearch] Allow elasticsearch type_name to be specified, optionally

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/service.yaml
Issue triggered when defining any service port as .Capabilities cannot be evaluated inside a range loop.
When attempted the following error is shown:
> rpc error: code = Unknown desc = render error in "fluentd-elasticsearch/templates/service.yaml": template: fluentd-elasticsearch/templates/service.yaml:14:46: executing "fluentd-elasticsearch/templates/service.yaml" at <.Capabilities.KubeVersion.GitVersion>: nil pointer evaluating interface {}.KubeVersion
=> [fluentd-elasticsearch] fix service template rendering

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/ruler-service.yaml, charts/prometheus-thanos/values.yaml
- fixes #159
- add service for thanso ruler
=> [prometheus-thanos] add thanos ruler service

.circleci/config.yml, charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/values.yaml
* Moves Compact component of Prometheus-thanos chart from a deployment to a stateful set to allow for configurable PVC storage to conform with recommended best practice.
* Removes replicaCount configurability to conform with best practice of running Compactor as singleton
- fixes #171
None
=> [prometheus-thanos] - Move Compact from Deployment to Statefulset

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
Adds values and readme strings for existing StorageClass parameter for Ruler and StoreGateway stateful sets
Signed-off-by GuyTempleton <guy.templeton@skyscanner.net>
Adds value and README strings for the `storageClass` variable already used by both the ruler and storeGateway stateful sets.
The use of them can be found:
* https://github.com/kiwigrid/helm-charts/blob/master/charts/prometheus-thanos/templates/store-gateway-statefulset.yaml#L119
* https://github.com/kiwigrid/helm-charts/blob/master/charts/prometheus-thanos/templates/ruler-statefulset.yaml#L154
- N/A
=> [prometheus-thanos] - Add values and README values for storageClass

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/compact-statefulset.yaml
Signed-off-by: Basilio Vera <basilio.vera@softonic.com>
After the migration of the compact component to a statefulset instead of a deployment there's a bug when using `volumenMounts` values.
The right indentation is now 12 instead of 14.
- fixes #
=> [prometheus-thanos] Fix compact volume mounts manifest indentation

charts/prometheus-pingdom-exporter/Chart.yaml, charts/prometheus-pingdom-exporter/README.md, charts/prometheus-pingdom-exporter/templates/deployment.yaml, charts/prometheus-pingdom-exporter/values.yaml
This PR adds optional annotations to the pingdom exporter pod. We need this in order to migrate the sensitive pingdom credentials into [Vault](https://www.vaultproject.io/).
We use a mutating webhook to grab secrets from Vault and push them into Kubernetes secrets, annotations on the pod are necessary to tell the init container where to find Vault, role to use, etc. e.g.
```
vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
vault.security.banzaicloud.io/vault-role: "default"
```
N/A
N/A
=> [prometheus-pingdom-exporter] Add optional pod annotations

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml
Getting so many errors due to the messages below.
```
2019-08-21T19:14:05Z docker time="2019-08-21T19:14:05.602349500Z" level=debug msg="Calling GET /v1.38/containers/json?all=1&filters=%7B%22label%22%3A%7B%22io.kubernetes.docker.type%3Dcontainer%22%3Atrue%7D%7D&limit=0"
```
In order to fix it, removed the leading `^` from the format.
You may test it in here https://regex101.com/r/MkIADf/1
=> removed `^` from the format

charts/prometheus-pingdom-exporter/Chart.yaml, charts/prometheus-pingdom-exporter/README.md, charts/prometheus-pingdom-exporter/templates/secret.yaml, charts/prometheus-pingdom-exporter/values.yaml
Similar to https://github.com/kiwigrid/helm-charts/pull/186, this PR adds the ability to assign annotations to the secret.
N/A
N/A
=> [prometheus-pingdom-exporter] Add optional annotations to secret

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/prometheusrule.yaml
Signed-off-by: Thomas FREYSS <thomas.freyss@gmail.com>
This issue fixes the FluentdRecordsCountsHigh prometheus alerting rule for the fluentd-elasticsearch chart, replacing a non existing metric with the appropriate one.
You can find the original issue in the fluent repo here: https://github.com/fluent/fluent-plugin-prometheus/issues/110
=> [fluentd-elasticsearch] Fix FluentdRecordsCountsHigh prometheus metric

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
* Align host paths with mount paths
* Add capability to customise livenessProbe
* Bump chart version
This PR reverts a change that was made in PR #101 to allow the paths that are mounted from the host to be aligned with the mount path we specify on the container. Previously the mount paths were hardcoded which makes it less flexible in situations where custom paths are needed (e.g. Docker on Windows).
As part of this PR I also added the ability to customise the liveness probe in order to be able to execute a custom command as this might also be needed in some cases, again thinking about Windows containers here.
- fixes #190 
=> [fluentd-elasticsearch] - Fixes for mounting host paths and livenessProbe

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
Add `objStoreConfigFile` value to `prometheus-thanos` chart for store, ruler, and compactor.
fixes #164 
The default for `objStoreType` isn't consistent across the three components. I have left this as it is but might be a gotcha when using these values. I have documented it in the README and a warning in the `values.yaml`.
Changing this default would break values for those that rely on this behaviour. Which is why I didn't want to do this as part of a patch release.
=> [prometheus-thanos] Add objStoreConfigFile value

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md
Signed-off-by: GuyTempleton <guy.templeton@skyscanner.net>
Tidies up the docs for the prometheus-thanos chart in a small number of ways:
* Alphabetical sorting for all supported variables
* Remove 4 duplicate compact variable listing (compact.affinity, compact.volumes, compact.volumeMounts and compact.tolerations)
* Consistent casing and naming across variable descriptions
* Minor grammatical and typo fixes
- N/A
=> [prometheus-thanos] - README cleanup

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Currently it's not possible to use alternative forms of liveness probes like [httpGet](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) as it's assumed a command is always used.
=> [fluentd-elasticsearch] make liveness probe kind configurable

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/bucket-web-deployment.yaml, charts/prometheus-thanos/templates/bucket-web-service.yaml, charts/prometheus-thanos/values.yaml
Adds the ability to deploy a deployment and service for the bucket web interface. 
Signed-off-by: GuyTempleton <guy.templeton@skyscanner.net>
Adds the ability to deploy a new deployment and service for the Thanos Bucket Web Interface. This can be useful for administrators of a Thanos install to verify compaction/downsampling is working as expected.
I've broken with the behaviour of all the other components here and set this to default to `enabled: false` as I believe it's of significantly lower value to most users than the other components.
- N/A
=> [prometheus-thanos] - Add bucket web interface deployment and service

charts/hawkbit-update-server/Chart.yaml, charts/hawkbit-update-server/README.md, charts/hawkbit-update-server/templates/deployment.yaml, charts/hawkbit-update-server/templates/poddisruptionbudget.yaml, charts/hawkbit-update-server/templates/service.yaml, charts/hawkbit-update-server/values.yaml
Support arbitrary service annotation (e.g. for prometheus scrape configuration)
Add PDB to ensure availability on k8s maintenance
Recreate strategy to avoid conflicts on database migrations
=> Support arbitrary service annotation

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml
Fixed a typo in daemonset.yaml (Introduced as recursion :() 
- fixes #
- [ x ] [DCO](https://developercertificate.org) signed
- [ x ] Chart Version bumped (if the pr is an update to an existing chart)
- [ x ] Variables are documented in the README.md
- [ x ] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)
=> [fluentd-elasticsearch] Fixed a typo in daemonset.yaml

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/metrics-service.yaml, charts/fluentd-elasticsearch/values.yaml
Signed-off-by: Ben Wilson <ben.wilson+github@ukfast.co.uk>
Adds a new value which lets us control whether the metrics service gets created, without having to create the service monitor. In essence this lets us decouple the servicemonitor and prometheus rule scrapes and remains backwards compatible, since the service will still get created when the servicemonitor gets enabled.
- fixes https://github.com/kiwigrid/helm-charts/issues/234
N/A
cc: @monotek  @axdotl 
=> [fluentd-elasticsearch] Allow metrics svc to be force generated

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/pod-security-policy.yaml
according https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ fix PodSecurity apiVersion
make chart compatible with k8s v1.16
@monotek @axdotl Please look at it once
=> fix deprecated PodSecurity apiVersion

charts/secret-replicator/Chart.yaml, charts/secret-replicator/README.md, charts/secret-replicator/templates/deployment.yaml, charts/secret-replicator/values.yaml
Removed hard-coded ImagePullSecrets from secret-replicator. In my deployment I don't need image pull secrets for deployment, and having hardcoded pull secret defined in deployment causes annoying (but harmless) errors in logs. Just clearing up noise.
Also, this allows actually customise secret name that is used for pulling images for this deployment.
=> [secret-replicator] Optional PullSecrets

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml
This fix ensures that if fluentd concat plugin generates error due to
timeout in processing, then message will be processed by other filters
and thus end in elasticsearch (even if not fully parsed).
Fixes error messages such as:
```text
[warn]: dump an error event:
error_class=Fluent::Plugin::ConcatFilter::TimeoutError
error="Timeout flush: node-problem-detector:default"
location=nil ...
```
For reference see:
https://github.com/fluent-plugins-nursery/fluent-plugin-concat#usage
or
https://github.com/helm/charts/pull/16871 under path
stable/sumologic-fluentd/files/file.source.containers.conf
Signed-off-by: Michał Sochoń <kaszpir@gmail.com>
- fixes #265 
Two notes:
- I believe bumping only patch version is sufficient, the code is backward compatible
- I have explicitly not indented the code …
=> [fluentd-elasticsearch] Ensure concat plugin does not drop messages.

charts/graphite/Chart.yaml, charts/graphite/README.md, charts/graphite/templates/statefulset.yaml, charts/graphite/values.yaml
Graphite-web uses `Etc/UTC` time zone by default, but it supports ability to use different one by setting up environment [GRAPHITE_TIME_ZONE](https://github.com/graphite-project/docker-graphite-statsd#graphite-web) value.
=> [graphite] Ability to use different time zone

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml
Ensure that field names are all lowercase.
Ensure that fields do not start with underscore.
Both above options makes fields indexable by elasticsearch, improving
ability to search for the desired content.
Unfortunately this will break dashboards/queries that expect
that certain fields are starting with underscore or are all in capital
letters.
Example:
`_PID` will become `pid`
`PRIORITY` will become `priority`
`_some_field` will become `some_field`
For reference please see:
https://github.com/fluent-plugin-systemd/fluent-plugin-systemd#filter-plugin-configuration
Signed-off-by: Michał Sochoń <kaszpir@gmail.com>
- fixes #264 
This is a breaking change.
I only bumped major version because it is just configuration change for fluentd itself.
=> [fluentd-elasticsearch] Add systemd field strip underscores and field lowercase to other sources

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/servicemonitor.yaml, charts/fluentd-elasticsearch/values.yaml
Signed-off-by: Robin Ketelbuters <robin.ketelbuters@gmail.be>
This PR adds support for filling in the relabelings and metricRelabelings fields in the ServiceMonitor definition for fluentd-elasticsearch.
For my specific use-case, I want to add labels to the `fluentd_tail_file_position` metric by extracting the information from the `path` label.
=> fluentd-elasticsearch: Support adding relabelings to ServiceMonitor

charts/graphite/Chart.yaml, charts/graphite/README.md, charts/graphite/templates/statefulset.yaml, charts/graphite/values.yaml
[initContainers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) helps us to fine-tune `Pod`'s kernel parameters on-demand whatever the need is.
=> [graphite] Ability to setup initContainers on-demand

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/bucket-web-deployment.yaml, charts/prometheus-thanos/templates/bucket-web-serviceaccount.yaml, charts/prometheus-thanos/templates/compact-serviceaccount.yaml, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/querier-serviceaccount.yaml, charts/prometheus-thanos/templates/ruler-serviceaccount.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-serviceaccount.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
To use Web Identity providers for IAM credentials for AWS EKS we need a kubrnetes service account with specific annotation.
This PR add a service account for each thanos component with an annotation option.
Related thanos fixed issue: https://github.com/thanos-io/thanos/issues/1494
=> [prometheus-thanos] Add parameter to create service accounts

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/bucket-web-deployment.yaml, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/templates/querier-deployment.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
Adds the ability to set priority or priorityClassName on all pod specs.
Adds the ability to independently set `priority` or `priorityClassName` on all pod specs within Prometheus-Thanos.
We have enabled pod priorities on our clusters and want to set our monitoring related pods as higher priority than our user workloads to ensure we don't risk losing visibility of our cluster state during fast scaling.
N/A
=> [Prometheus-Thanos] - Add podPriority and podPriorityClassName

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/querier-deployment-hpa.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset-hpa.yaml, charts/prometheus-thanos/values.yaml
Adds an autoscaling config for the querier and store gateway in the
prometheus-thanos chart.
The metrics to scale on can be defined in the autoscaling sections of
the respective objects as MetricSpecs.
Autoscaling is disabled by default.
- fixes #285
=> [prometheus-thanos] Add Thanos querier and store gateway autoscaling

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/bucket-web-deployment.yaml, charts/prometheus-thanos/values.yaml
As of version 0.9 there was a rationalisation of startup of HTTP components of Thanos. This meant that the `bucket web` component moved from being served on port `8080` to `10902` as with the other HTTP components. (See https://github.com/thanos-io/thanos/pull/1687). This isn't strictly necessary to still port-forward to the container as long as users correctly figure out the port however could lead to usability issues and issues with other tooling.
N/A
=> [prometheus-thanos] - Allow bucket web httpPort specification

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
Signed-off-by: GuyTempleton <guy.templeton@skyscanner.net>
Realised this morning that #287 accidentally managed to bump the app version as well as the chart version (made my usual mistake of confusing the two to begin with.) Came back to correct my mistake and realised the upstream v0.10.1 release has been cut.
Pulls in the fix documented here: https://github.com/thanos-io/thanos/blob/v0.10.1/CHANGELOG.md#v0101---20200123 
Note that as per the [thread comment here](https://github.com/thanos-io/thanos/pull/2015#issuecomment-577586302) the querier needs to be updated to this release to resolve the issue, not just the sidecar despite the release note implying this, hence why it benefits this chart.
N/A
=> [prometheus-thanos] - Update to v0.10.1

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml, charts/prometheus-thanos/values.yaml
Makes the index cache for the store gateway configurable. This now
supports the use of Memcached instead of local memory as the index cache
store (released in [Thanos 0.10.0](https://github.com/thanos-io/thanos/releases/tag/v0.10.0).
- fixes #289
=> [prometheus-thanos] Make the cache for the store gateway configurable

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/compact-statefulset.yaml, charts/prometheus-thanos/templates/ruler-statefulset.yaml, charts/prometheus-thanos/templates/store-gateway-statefulset.yaml
The prometheus-thanos chart was breaking (producing invalid yaml) when installed with disabled `compact.persistentVolume` and no custom volumes (both are defaults).
- fixes #296
- most probably also #255 
In `compact-statefulset.yaml`, I have:
- fixed indentation
- fixed the logic bug (see details in respective commit message)
- (**moving to separate PR**) improved readability by extracting `{{ $values := .Values.compact }}` at the top of template
I also noticed the same logic issue exists in `store-gateway-statefulset.yaml`, so I ported all the above fixes there as well.
=> [prometheus-thanos] Fix compact and store-gateway templates breaking when there are no extra volumes defined

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/role.yaml
Fix fluentd-elasticsearch Role for Kubernetes >1.15
=> [fluentd-elasticsearch] Fix Role for k8s >1.15

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR allows to change `@type` in output section. This may be useful when `elasticsearch_dynamic` type is the desired way to ship the logs. Another part of this solution - "LOGSTASH_PREFIX" is already there
FTR please see this comment: https://github.com/kubernetes/kubernetes/issues/23001#issuecomment-462538401
@monotek  @axdotl I've tested it in my environment with:
```
elasticsearch:
outputType: elasticsearch_dynamic
logstashPrefix: "logstash-${record['kubernetes']['namespace_id']}"
```
Could we please get this merged?
- [ x ] [DCO](https://developercertificate.org) signed
- [ x ] Chart Version bumped (if the pr is an update to an existing chart)
- [ x ] Variables are documented in the README.md
- [ …
=> [fluentd-elasticsearch] Allow to switch output type.

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/values.yaml
Set the default type of the metrics service created.
Without this the service generated does not have a valid type.
=> [fluentd-elasticsearch] Default metrics service type

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/values.yaml
Signed-off-by: Jared Burns <jared.burns@nike.com>
This PR adds a default value to the `env` config variable of the fluentd-elasticsearch chart, which allows this chart to be templated using the helm 3 client.
- fixes #310 
I also added a default value for `secret` in this PR. It isn't strictly required, but it a best practice.
=> [fluentd-elasticsearch] Add default values for env and secrets

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/bucket-web/service.yaml, charts/prometheus-thanos/templates/querier/service.yaml, charts/prometheus-thanos/templates/ruler/service.yaml, charts/prometheus-thanos/templates/store-gateway/service.yaml, charts/prometheus-thanos/values.yaml
Adds the ability to give custom annotations to services. In our use case this helps change the `alb.ingress.kubernetes.io/healthcheck-path` to support a 302 provided by the querier.
=> [prometheus-thanos] Allow annotations on services

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml, charts/prometheus-thanos/values.yaml
Adds a flag that allows opting in to using binary index headers (as
released in Thanos v0.11.0). The feature is still experimental.
- fixes #316
=> [prometheus-thanos] Allow the use of binary index headers

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml
Fixes a bug where the template incorrectly chomps whitespace on the
right and by that swallows a newline character and makes the rendered
object invalid. When opting in to binary index headers, the broken chart
merges the flag `--experimental.enable-index-header` and the next line,
`ports:` into one: `--experimental.enable-index-headerports:`
This fixes it.
- fixes #321 
=> [prometheus-thanos] Fix syntax when opting in to binary index headers

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/servicemonitor.yaml, charts/fluentd-elasticsearch/values.yaml
The value of `jobLabel` in a `ServiceMonitor` defines the label of the scraped service whose value should be used as `job_name` by Prometheus. However, it looks like in the chart it was being used as if it was meant to be the actual value one wanted to use for the job. Because of
this, scraped metrics would end up with, say, `fluentd-elasticsearch-metrics` (the name of the scraped `Service`) instead of `fluentd-elasticsearch`.
This is particularly tricky since it would interact badly with the provided `PrometheusRules`. For example, `FluentdNodeDown`, that would normally be triggered when there are no fluentd pods running, gets defined as `up{job="fluentd-elasticsearch"} == 0`, but because there are no
samples generated for that job, it remains forever green!
We now use …
=> [fluentd-elasticsearch] Fix jobLabel in ServiceMonitor

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Add's support for setting the awsSigningSidecar's remote read timeout, as added in the `1.0` release of `aws-es-proxy` (which this PR upgrades to)
https://github.com/abutaha/aws-es-proxy/releases/tag/v1.0
Previously the default seemed to be taken from GoLang|OS; leading to ~15 minute downtime if connections to ElasticSearch are terminated/dropped on the remote side; e.g during an AWS ElasticSearch domain upgrade.
The default value chosen in the chart here is the same as the default in the `aws-es-proxy` [code](https://github.com/abutaha/aws-es-proxy/blob/4306126ddc375b65d26d1d85b3e08e8f8532641e/aws-es-proxy.go#L438) (15 seconds).
=> [fluentd-elasticsearch] Add support for setting the awsSigningSidecar's remote read timeout

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
@axdotl  
@monotek  
Since Fluentd config [accepts multiple hosts](https://docs.fluentd.org/output/elasticsearch#hosts-optional) in its config, I would like to be able to provide them through the chart. The new `hosts` array parameter allow for multiple elasticsearch hosts to be configured as target.
Deprecated both parameters 
```yaml
elasticsearch:
host: elasticsearch-client
port: 9200
```
in favor of 
```yaml
elasticsearch:
hosts: ["elasticsearch-client:9200"]
```
If you are using the AWS Sidecar, only the first host in the array is used. [Aws-es-proxy](https://github.com/abutaha/aws-es-proxy) is limited to one endpoint.
- fixes #330
I could not test changes done to the aws-es-proxy sidecar, if someone can help me with that part
=> [fluentd-elasticsearch] Allow multiple hosts in config

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
We at SAP are using "fluentd-elasticsearch" image often and require the following parameters to be remotely configurable from the values.yaml file
1. Conditioning on logstash_format and using Env
2. Adding reload_on_failure and using Env
3. Adding reload_connections and using Env
4. Using Env for all buffer block"
- fixes #339
=> [fluentd-elasticsearch] Adding new configurations for elasticsearch plugin

charts/graphite/Chart.yaml, charts/graphite/templates/service.yaml, charts/graphite/templates/statefulset.yaml
Added missing UDP port for plain carbon interface on port 2003 in statefullset and services. This UDP interface needs to be enabled by setting option 
ENABLE_UDP_LISTENER = True
in carbon.conf in the values.yaml.
It is still one of the best interfaces for pushing bulk amounts of metrics in, if you don't care about guaranteed delivery.
I tested the modifications in my own cluster and it works fine. Also, can still telnet to 2003 TCP port.
=> graphite - expose carbon UDP port

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/clusterrole.yaml, charts/fluentd-elasticsearch/templates/clusterrolebinding.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/templates/metrics-service.yaml, charts/fluentd-elasticsearch/templates/pod-security-policy.yaml, charts/fluentd-elasticsearch/templates/prometheusrule.yaml, charts/fluentd-elasticsearch/templates/role.yaml, charts/fluentd-elasticsearch/templates/rolebinding.yaml, charts/fluentd-elasticsearch/templates/service-account.yaml, charts/fluentd-elasticsearch/templates/service.yaml, charts/fluentd-elasticsearch/templates/servicemonitor.yaml
Is this a BUG REPORT or FEATURE REQUEST? :
FEATURE REQUEST
Version of Helm and Kubernetes:
Helm v3.1.2 and Kubernetes v1.15.9
Which chart in which version:
9.0.0
What happened:
Avoid diff in our CI because of k8s removing this label deprecated label constantly.
- fixes #343
=> fix(labels): remove deprecated label

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
A new feature to have a configurable [index_name](https://docs.fluentd.org/output/elasticsearch#index_name-optional).
This should enable people using this chart to configure the index_name to their liking and requirements.
Before the PR it was a choice between a large `fluentd` index or a daily `<logstashPrefix>-%Y.%m.%d` index.
- N/A
N/A
=> [fluentd-elasticsearch] Make index_name changable

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR provides a way to disable setting the `OUTPUT_HOSTS` environment variable from the `elasticsearch.hosts` value. This feature allows users to manually set `OUTPUT_HOSTS` using a secret or alternative method if they desire.
- fixes #348 
N/A
=> [fluentd-elasticsearch] Provide option to disable settings elasticsearch hosts

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
Adding reqeust timeout configuration variable.
This is useful when Elasticsearch cannot return response for bulk request within the default of 5 seconds.
https://github.com/uken/fluent-plugin-elasticsearch#request_timeout
- fixes #
=> [fluentd-elasticsearch] adding request timeout config

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
Update prometheus-thanos from 0.12.0 to 0.12.2. This version of thanos include a bug fix that would prevent thanos from deleting partial block and would cause a lot of spam.
See https://github.com/thanos-io/thanos/blob/v0.13.0/CHANGELOG.md#v0122---20200430
0.12.1 is skipped because it does not fix this bug entirely while 0.12.2 does.
=> [prometheus-thanos] update thanos to 0.12.2

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
Bump thanos version from 0.12.2 to 0.13.0.
=> [prometheus-thanos] update thanos to 0.13.0

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md
This PR adds to the documentation for upgrading to version 8.x of this chart, advising how to handle the elasticsearch.host/port change using `--set`
- fixes #336 
Chart version not bumped because this is a documentation change only.
=> [fluentd-elasticsearch] Update README.md to explain --set syntax change for 8.0

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/templates/configmaps.yaml
Fix typo'd single quote
A typo in the ENABLE_ILM environment variable didn't get caught previously  . 
=> [fluentd-elasticsearch] typo in ENABLE_ILM environment variable

charts/fluentd-elasticsearch/Chart.yaml, charts/fluentd-elasticsearch/README.md, charts/fluentd-elasticsearch/templates/configmaps.yaml, charts/fluentd-elasticsearch/templates/daemonset.yaml, charts/fluentd-elasticsearch/values.yaml
This PR adds `elasticsearch.suppressTypeName` as a chart parameter in order to leverage the `suppress_type_name` option on the fluentd-elasticsearch plugin.
- fixes #381
Please note that this PR will not work at this moment! At the time this PR is being opened, the referenced fluend-elasticsearch image version (3.0.4) is in PR but not yet been published. (https://github.com/kubernetes/kubernetes/pull/93116)
I'm submitting this PR now so it can be reviewed and I can incorporate any feedback as needed.
Note that I have tested both the new fluentd-elasticsearch image 3.0.4 (published as a fork) as well as the changes I'm submitting here (published to a private helm repo), …
=> [fluentd-elasticsearch] (PREVIEW - DO NOT MERGE) Add suppressTypeName parameter to eliminate ES 7 deprecation warnings

charts/fluentd-elasticsearch/Chart.yaml
Based on the values.yml, the default version/tag of fluentd is `v3.0.4`
Show correct application version.
=> [fluentd-elasticsearch] fix app version to 3.0.4

charts/secret-replicator/Chart.yaml, charts/secret-replicator/README.md, charts/secret-replicator/templates/deployment.yaml, charts/secret-replicator/values.yaml
(this is a retry of https://github.com/kiwigrid/helm-charts/pull/417, since I couldn't get signed commits to work with the a rebase, due to my n00bness)
Adds optional support to the secret-replicator chart for:
1. Passing the `SECRET_NAMESPACE` env var 
2. Setting the pod `securityContext`
3. Setting the container `securityContext`
Why do we need this?
Firstly, in our deployment, we want to isolate secret-replicator from the secrets which it generates.
Secondly, setting `securityContexts` allows "locking-down" the pod in sense of disabling privileged mode, enforcing readOnlyRootFilesystem (only at the container level).
All the changes I've prosposed are opt-in, and I've updated the README accordingly.
=> Retry for PR with signed commits!

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/querier/deployment.yaml
This PR wraps the Thanos Querier additional flags in template with `"`. This allows us to pass values that have new line characters and/or quotation marks in them. For instance, the `tracing.config` flag (see [here](https://github.com/thanos-io/thanos/blob/master/docs/components/query.md)) accepts a YAML string, but currently when the template is rendered with a YAML valid string the output (rendered template) the querier does not start because the provided valid YAML gets broken after the template is rendered.
Signed-off-by: Emre Kartoglu <iemrek@gmail.com>
* I've tested the changes in a private setup.
=> [prometheus-thanos] Wrap thanos querier additional flags with quotes

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compactor/statefulset.yaml, charts/prometheus-thanos/templates/querier/deployment.yaml, charts/prometheus-thanos/templates/query-frontend/deployment-hpa.yaml, charts/prometheus-thanos/templates/query-frontend/deployment.yaml, charts/prometheus-thanos/templates/query-frontend/service.yaml, charts/prometheus-thanos/templates/query-frontend/serviceaccount.yaml, charts/prometheus-thanos/templates/receiver/hashring-configmap.yaml, charts/prometheus-thanos/templates/receiver/service.yaml, charts/prometheus-thanos/templates/receiver/serviceaccount.yaml, charts/prometheus-thanos/templates/receiver/statefulset.yaml, charts/prometheus-thanos/templates/ruler/statefulset.yaml, charts/prometheus-thanos/templates/store-gateway/statefulset.yaml, charts/prometheus-thanos/values.yaml
It adds the Query Frontend and Receiver components to the chart.  
https://github.com/thanos-io/thanos/blob/master/docs/components/query-frontend.md
https://github.com/thanos-io/thanos/blob/master/docs/components/receive.md 
It also allows for simpler tracing configuration with all components which support it:
https://github.com/thanos-io/thanos/blob/master/docs/tracing.md
* Tested within a local `kind` cluster running k8s v1.16.15
=> [prometheus-thanos] Add Receiver, QueryFrontend and simplify tracing config

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/compactor/service.yaml, charts/prometheus-thanos/templates/receiver/service.yaml, charts/prometheus-thanos/values.yaml
Signed-off-by: Emre Kartoglu <iemrek@gmail.com>
Co-authored-by: Tony Di Nucci <tony.dinucci@skyscanner.net>
This adds a k8s Service definition for the Thanos Compactor component so we can monitor it using its HTTP `/metrics` endpoint.
This also adds a Service port mapping for the Thanos Receiver component for the same reason i.e. monitoring using the HTTP `/metrics` endpoint.
I've tested the changes in a local setup.
=> [prometheus-thanos] Add k8s Service for thanos compactor

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/receiver/service.yaml
Signed-off-by: Emre Kartoglu <iemrek@gmail.com>
The Service definition for Thanos Receiver did not have the grpc port listed. The port is there in the values file, and I can't think of a reason why it shouldn't be in the Service definition too, therefore I'm treating this change as a patch.
I've tested the changes on my local kind cluster.
=> [prometheus-thanos] Add grpc port to thanos receiver service

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
=> [prometheus-thanos] upgrade to v0.18.0

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/templates/receiver/service.yaml
Some system (e.g. Istio) depend on even headless services containing port mappings - no matter whether the mapping can change the port or not.
=> [prometheus-thanos] Some systems (e.g. Istio) need even headless services to define ports

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/ruler/statefulset.yaml, charts/prometheus-thanos/values.yaml
Signed-off-by: George Koufoudakis <georgios.koufoudakis@finbourne.com>
This PR adds imagePullSecrets to Thanos Ruler StatefulSet for pulling kiwigrid/k8s-configmap-watcher using  docker credentials.
I hope you find this useful
=> [prometheus-thanos] Add imagePullSecrets to ruler

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/values.yaml
- Update thanos components to 0.20.2 in order to include all fixes from that version
=> [prometheus-thanos] Update thanos to 0.20.2

charts/prometheus-thanos/Chart.yaml, charts/prometheus-thanos/README.md, charts/prometheus-thanos/templates/query-frontend/deployment.yaml, charts/prometheus-thanos/values.yaml
This PR adds the ability to use caching in the query-frontend component
- I tried to get it to work using the `queryFrontend.additionalFlags` parameter, but I was constantly getting a YAML parsing error even though it was a valid YAML. These changes add specific parameters for configuring the query-frontend cache.
=> [prometheus-thanos] : Add support for query-frontend caching

charts/error-pages/Chart.yaml, charts/error-pages/templates/ingress.yaml
We are upgrading our kubernetes cluster to v1.22 and the current chart uses a (now) deprecated kubernetes API
You can see here that it is [being deprecated](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) and then [in this list](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#ingress-v1-networking-k8s-io) you can see that it is not being included at all
- fixes #454 
=> [error-pages] Update kubernetes ingress api to `v1`
